version: "{build}"

skip_tags: true

environment:
  matrix:
    - FEATURE: HUGE
# disabled
#    - FEATURE: SMALL
#    - FEATURE: NORMAL
#    - FEATURE: BIG

matrix:
  fast_finish: true

before_build:
  # Use Visual Studio 2015 compiler tools (default is 2012)
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64'

build_script:
  - ci/appveyor.bat

test_script:
  - cd src/testdir
    # Testing with MSVC gvim
  - path C:\Python35-x64;%PATH%
  - nmake -f Make_mvc.mak VIMPROG=..\gvim
  - nmake -f Make_mvc.mak clean
    # Testing with MSVC console version
  - nmake -f Make_mvc.mak VIMPROG=..\vim

# vim: sw=2 sts=2 et ts=8 sr
