version: "{build}"

image: Visual Studio 2015

skip_tags: true

environment:
  matrix:
    - FEATURE: HUGE
# disabled
#    - FEATURE: TINY
#    - FEATURE: NORMAL
#    - FEATURE: BIG

matrix:
  fast_finish: true

before_build:
  # Use Visual Studio 2015 compiler tools (default is 2012)
  - 'setlocal ENABLEDELAYEDEXPANSION'
  - 'call ver'
  - 'set "VSWHERE=%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"'
  - >
    if exists "%VSWHERE%" (
      for /f "usebackq delims=" %%i
      in (`"%VSWHERE%" -products * -latest -property installationPath`) 
      do (set VCVARSALL="%%i\VC\Auxiliary\Build\vcvarsall.bat")
    )
  - >
    if not exists %VCVARSALL% (
      set "VCVARSALL=%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
    )
  - 'call %VCVARSALL% x86_amd64'

build_script:
  - ci/appveyor.bat

test_script:
  - cd src/testdir
    # Testing with MSVC gvim
  - path C:\Python311-x64;%PATH%
  - nmake -f Make_mvc.mak VIMPROG=..\gvim
  - nmake -f Make_mvc.mak clean
    # Testing with MSVC console version
  - nmake -f Make_mvc.mak VIMPROG=..\vim

artifacts:
  - path: src/vim.exe
    name: vim
  - path: src/gvim.exe
    name: gvim

# vim: sw=2 sts=2 et ts=8 sr
