version: "{build}"

image: Visual Studio 2015
#image: Visual Studio 2022

skip_tags: true

environment:
  matrix:
    - FEATURE: HUGE
# disabled
#    - FEATURE: TINY
#    - FEATURE: NORMAL
#    - FEATURE: BIG

matrix:
  fast_finish: true

before_build:
  # Use Visual Studio 2015 compiler tools (default is 2012)
   - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64'
  # - 'call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64'

build_script:
  - ci/appveyor.bat

test_script:
  - cd src/testdir
    # Testing with MSVC gvim
  - path C:\Python35-x64;%PATH%
  - nmake -f Make_mvc.mak VIMPROG=..\gvim
  - nmake -f Make_mvc.mak clean
    # Testing with MSVC console version
  - nmake -f Make_mvc.mak VIMPROG=..\vim

artifacts:
  - path: src/vim.exe
    name: vim
  - path: src/gvim.exe
    name: gvim

# vim: sw=2 sts=2 et ts=8 sr
