# Cross-platform build pipeline + NPM publish

name: $(Build.SourceVersion)
jobs:
# - job: Linux
#   pool:
#     vmImage: 'Ubuntu 16.04'
#   steps:
#   - script: sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libegl1-mesa-dev mesa-utils mesa-utils-extra ragel
#   - template: .ci/esy-build-steps.yml
#   - template: .ci/prebuilt-library/publish-platform-prebuilt.yml
#     parameters:
#       platform: "platform-linux"

# - job: MacOS
#   pool:
#     vmImage: 'macOS 10.13'
#   steps:
#   - script: brew update
#   - script: brew install libpng
#   - template: .ci/esy-build-steps.yml
#   - template: .ci/prebuilt-library/publish-platform-prebuilt.yml
#     parameters:
#       platform: "platform-darwin"

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: .ci/esy-build-steps.yml
